# CatBoost YetiRankPairwise 排序模型配置。
name: cat_yetirank_pairwise
family: catboost
enabled: true
output_dir: ./model/catboost
num_boost_round: 200
features:
  input_window: 12
  feature_type: "39"
params:
  max_relevance: 30
  loss_function: YetiRankPairwise
  task_type: GPU
  devices: "4"
  learning_rate: 0.03
  depth: 5
  l2_leaf_reg: 18.0
  random_seed: 42
  verbose: false
  allow_writing_files: false
